# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
      path: stderr
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    shadow: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - goimports
    - ineffassign
    - gosimple
    - staticcheck
    - revive
    - typecheck
    - unused

issues:
  exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache
    - go
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    - G104
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name