volumes:
  auth_postgres_volume:

services:
  auth_pg:
    image: postgres:14-alpine3.17
    container_name: auth_pg
    env_file:
      - prod.env
    ports:
      - "54321:5432"
    volumes:
      - auth_postgres_volume:/var/lib/postgresql/data
    networks:
      - auth

  auth_migrator:
    container_name: auth_migrator
    image: $(MIGRATOR_IMAGE)
    build:
      context: .
      dockerfile: migrator/migrator-prod.Dockerfile
    env_file:
      - prod.env
    restart: on-failure
    networks:
      - auth

networks:
  auth:
    external: true